# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_denuncia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('idnews', models.AutoField(db_column='idNews', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('teaser', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.CharField(blank=True, max_length=600, null=True)),
                ('imageUrl', models.CharField(blank=True, db_column='imageUrl', max_length=600, null=True)),
            ],
        ),
    ]
